#!/bin/bash

mkdir -p ~/.config/nvim/
ln -sf ~/dotfiles/init.vim ~/.config/nvim/init.vim

curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

ln -sf ~/dotfiles/vim ~/.vim
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/gitconfig ~/.gitconfig
ln -sf ~/dotfiles/bash_profile ~/.bash_profile
ln -sf ~/dotfiles/bash_aliases ~/.bash_aliases
ln -sf ~/dotfiles/git-completion.bash ~/.git-completion.bash
ln -sf ~/dotfiles/tmux.conf ~/.tmux.conf
git submodule init
git submodule update
